name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3            

      - name: Set up OpenGL Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libglm-dev libgtest-dev

      - name: CMake Action
        uses: threeal/cmake-action@v1.3.0

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tests (Replace with your test command)
        run: |
          cd build
          ctest
